name: locaview
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  location: ^5.0.3
  get: ^4.6.6
  logger: ^2.0.2+1
  flutter_smart_dialog: ^4.9.5+2
  intl: ^0.19.0
  latlong2: ^0.9.1
  http: ^1.2.0
  fpdart: ^1.1.0
  get_it: ^7.6.7
  navigation_with_mapbox: ^0.0.7
  geolocator: ^11.1.0
  flutter_map: ^6.1.0
  permission_handler: ^11.3.1
  flutter_mapbox_navigation: ^0.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.14.1
  nb_utils: ^7.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/route_ic.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
